### ISSUE TITLE
Project Discussion

### ISSUE THREAD

**Issue by ahunker** [ahunker/Hamilton-Project#1]
Welcome to the Hamilton Project as we're currently calling it. So I thought we should throw around some ideas about what we'll be analyzing and trying to visualize in this project. Some ideas that instigated this project was looking at it from a historical perspective, like dates, places, and people along with references to historical documents within the lyrics. Another idea was looking at repetition in the songs and linking certain phrases to specific characters. I've uploaded all of the song lyrics in the Source Texts folder if you want something to look at as a reference point when thinking of ideas.

@bsf15 @ebeshero @RJP43

**Comment by ahunker** [comment]
So, I've been listening to the Hamilton soundtrack for inspiration and I've come up with some ideas as to what we could be looking for in the texts. I really like the idea of finding words or phrases that are repeated in more than one song such as "satisfied", "history has its eyes on you", or "who lives, who dies, who tells your story?".  There are a lot of these if you study the lyrics.
 Another thing I noticed about the musical is that names are mentioned a lot. Due to its historical connections, there are a lot of people mentioned and even the main characters consistently use names. I'd like to compare this with how much certain characters talk. So, is the character who is talked about the most the one who talks the most? 
 I'd like to grab place names and dates as. If this project were to be continued or if we have time, labeling places on a map might be an interesting visualization or perhaps a timeline on which we can place the songs in comparison to history. 
 @bsf15 Let me know what you think about these ideas. I know it was your idea to originally look at repetitive words and phrases, so I would be happy to let you have control over that part of the project and I'd take the people.
 In general, we need to figure out how we want to tag this structurally. Perhaps we could take an act each in order to split the work. We need to figure out a weekly meet time as well. Let me know what would work best for you.

**Comment by bsf15** [comment]
I really like the idea of marking up character names and finding out which characters end up being mentioned most and identifying if the most mentioned character has the most lines in the musical. I think it could be interesting to even match up which character discusses other characters the most, like for example does Burr mention Hamilton the most out of all the other characters and which character references Angelica the most. 
The place names and dates are also a really good idea for things to look into since they are mentioned often. Even doing a small markup of a timeline for just the musical itself if we don't have time to apply it to actual history would be really cool I think.
I'd totally be up for looking for the repeated words and phrases also and you taking the people. Then maybe we could both mark up places and dates, and you could take one act and I could take another perhaps? I feel like for both the characters and repeated phrases, depending on how we go to tag everything, just doing an act could be hard since especially for the phrases and words they carry over throughout the whole musical. We'll definitely have to look into all options though so we are able to do everything we plan in time without spreading ourselves too thin or anything.
For times to meet up, Mondays and Wednesday right after class until 4:00 I am free. That would work really well for me, but I am also open on Tuesdays and Thursdays from 3:45 until 5:15. Just let me know what also works for you because I can definitely work with my schedule to make another time work for the weekly meet up.

**Comment by ahunker** [comment]
The only times that work for me during the week is before 1:00 pm or after 5:15 pm on Tuesday, I can also meet before our Intro to Creative Writing class on Monday, Wednesday, and Friday. If none of those work, I can be back on campus about 5:30 pm or later on Monday, Wednesday, and Friday. I was just wondering if you're a resident or commuter by the way?

**Comment by ahunker** [comment]
So, we will be having our first meeting this Wednesday at 9 am in Powers Hall. We'll probably just finalize our ideas and decide on what our aim is with this project.

**Comment by RJP43** [comment]
Great job @ahunker and @bsf15 for being on top of setting up a first meeting time. I'd like to attend this first meeting. Are you guys meeting in PH lounge?

**Comment by bsf15** [comment]
That sounds good! And yep, we are meeting in PH lounge.
