### ISSUE TITLE
Vis(ualization) page 

### ISSUE THREAD

**Issue by ebeshero** [ahunker/Hamilton-Project#11]
@bsf15 and @ahunker I think the new vis.html page looks great! http://hamilton.newtfire.org/vis.html
But here are some suggestions that might be helpful for the presentation tomorrow and for visitors to your site: You've posted the `.png` image file of the network graph, which is ok on a first look, but someone who really wants to read your network graph is going to want to zoom in--and this isn't great for that. What I'd suggest is this: Have the `.svg` loaded on the site, and make your image link directly to it, so if we click on the network graph, it opens up on its own in the browser without the webpage around it. (Or you could do that with the `.png` file too, if you think it looks better when you view it on its own in a browser window.)  I've done something like that here with the graphs on my Mitford project site: http://digitalmitford.org/visual.html Try clicking on the graphs on that page. 

You'll want to try to add labels to the graph: you can do that in Cytoscape by right-clicking in the image: a drop-down menu comes up and lets you add "annotations" (which are basically ways of adding labels like you see on my page). 

@RJP43 What do you think? You've done lots of mounting of network graphs on your site--so I think you'll have some ideas here. :-)

**Comment by ebeshero** [comment]
Ideas to think about:
* One thing we might play with (and haven't yet on any projects so far) is to see if we can add some JavaScript functionality to these SVG image exports. That would involve a different strategy to mount the Cytoscape SVG on the webpage after tinkering with its viewport in oXygen, and getting a sense of how the nodes and edges are labelled in the Cytoscape output file. 

* One thing we *have* done with other projects is something @bsf15 and I discussed a little yesterday: Make new little filtered networks based on the same giant network for all of Hamilton. To do this, I'd recommend:
1) **Save** your style that you made for your nodes and edges (there is a way to do that in Cytoscape, so that when you import a new graph you can select the style you created for coloring nodes, edge, etc.).
2) Redo your XQuery, or make sure your XQuery TSV output contains information on Acts 1 or 2 and song titles.
3) Import the expanded TSV into Cytoscape, and identify the information about Acts and Titles as, I think, **edge attributes** since your source nodes are referring to particular targets in a particular act, and in a particular song. 
4) You can then add styling to color your edges differently based on what part of the musical they come from! AND you can select all the nodes that share a particular **kind** of edge, and use those to make a smaller network graph out of your main graph. 

This might be best to try to do together in a project meeting, but what do you think? @bsf15 @ahunker @RJP43

**Comment by ahunker** [comment]
@bsf15 I'll let you adjust the vis.html since that's your work. I don't want to mess with it so you'll know what to expect when presenting on Friday. This weekend, I'll try to make some SVG that corresponds with JavaScript, like maybe a table that pops up when you click on a graph. 
I just created a map that has all the placeNames from the entire musical. I am having trouble with the KML files though. I cannot get the description to appear and the description will contain the songs in which that place appears, which would help with drawing a more in-depth analysis of it. I used the XSLT from XQuery 3 that @ebeshero provided and I've played around with it, but I can't get it to work. I could use some help debugging so I can update the map eventually.
