### ISSUE TITLE
Project Feedback 

### ISSUE THREAD

**Issue by RJP43** [ahunker/Hamilton-Project#13]
Pitt-Oakland and others comment on this issue with your comments on today's presentation.

**Comment by amk231** [comment]
I understand that the project is not done yet so I tried to make suggestions only on the sections that are most complete. First off, I really enjoyed your network analysis graph. It is an extremely useful layout where you found a way to allow the edges to refer back to the originating node when the character refers to his/herself. This actually helps me fix an issue with my own network analysis where the edges overlap completely when two characters reference each other, so thanks! Though not necessary, I think it would be beneficial to allow the viewer to interact with the graph in two ways: Adding highlight and magnify options. Allowing the viewer to highlight can emphasize (plus make it easier to see) a particular interaction, either between to characters or throughout an act. I suggest adding a magnifier merely because some of the names are hard to see, and if you physically zoom on the page, the quality suffers. I believe you can add this in using CSS or Javascript, and how, if you do plan to implement this, is up to you (hover, new tab, etc.). You can look up some options in w3chools or a forum. 
       The map is also a great visualization for your project and is very interesting. You state that you noticed a difference in acts where specific locations were mentioned and I think you could create a SVG line graph to demonstrate these differences throughout time in the acts. I also like how the song index page is set up (seems like it takes a lot of work to create all those individual html pages!) where you can select which types of text you would like to highlight, and I can imagine quite a few situations where this function would be extremely useful to a viewer. 
       I have some smaller suggestions for you to implement into your project as well. For one thing, you could improve your about page by adding in a drop down menu to the about menu tab itself instead of three new links on the page. This would leave more room for whatever text/ images you add in without making the viewer scroll. Another thing is the background sharply repeats as you scroll down, and it is difficult to tell if you meant to do this or not. Though the background goes well with your theme it may be better to search for another similar image with a more constant color so that the transition is not so noticeable. Sometimes, if the picture is big enough, you can crop out the change, but often this actually just makes more unsightly transitions.
Overall the project looks great and I will be sure to check back in two weeks to see the final project! 
~Angela Klinger :)

**Comment by ebeshero** [comment]
@ahunker @bsf15 and @amk231 Audrey and Bri-- I was thinking about Angela's thoughtful feedback, and wanted to show you something you could experiment with for your backgrounds. The issue, of course, is the way webpages tile backgrounds when you have a long or wide page, and of course, the Hamilton background isn't quite high resolution enough to prevent the unintended effect of making a giant tile repeating with definite intersecting lines. One thing I've tried in the past, when I really like a background like this, is to try making tiny pieces of it that might tile more smoothly or in a way that isn't so noticeable.

I don't know if you'll like this, so please feel free to delete and play with as you wish! But what I did was open your current background image (`back2.jpg`) in an image editor (I've got Photoshop installed, but you could use anything convenient), and take a tiny snip of it--a longish, narrow piece from the center. I named this file `backPiece.jpg`, saved it in your directory of website files, and referenced it in the CSS controlling your `vis.html` page (`vis.css`): We can preview how it looks just in this GitHub repo with a handy prefix: `http://htmlpreview.github.io/?` that you put just in front of the GitHub repo page where it typically displays just your code, like so:
`http://htmlpreview.github.io/?https://github.com/ahunker/Hamilton-Project/blob/master/Hamilton_WebPage/vis.html`
So [here's how it looks](http://htmlpreview.github.io/?https://github.com/ahunker/Hamilton-Project/blob/master/Hamilton_WebPage/vis.html)!  

It's interesting that the smaller and smaller the pieces you make, the more a tiny-tiled background starts to look like fabric...Anyway, I hope this gives you some ideas! 
And thank you, Angela, for the helpful comments! :-)

**Comment by RJP43** [comment]
Also reference Issue #14 #15 #16 #17
