### ISSUE TITLE
Phrases Line Graph XSLT and all-in-one TEICorpus of Hamilton

### ISSUE THREAD

**Issue by ebeshero** [ahunker/Hamilton-Project#21]
*Note: for future reference, in this issue we developed two ways to process an SVG line-graph with data pulled from a collection of files.*

@bsf15 and @ahunker both: BE SURE TO DO A GIT PULL: I've just made two new commits to your repo, to help out with the frequency line graph. 

@ahunker I pulled in your XSLT for the line graph, remembering there were some things we were stuck on yesterday (Friday) when we met. I remember you mentioning you weren't quite sure how to get the connecting lines to work, moving from one TEI file to the next in your `<xsl:for-each>`, and right, it's not possible to reach a file in a collection using XPath axes (at least not in XSLT). So I took the liberty of writing [an XSLT file](https://github.com/ahunker/Hamilton-Project/blob/master/Visualizations/PhrasesFrequency/teiCorpusTransform.xsl) to bundle all 46 Hamilton songs (as you have in them in the PhrasesFrequency directory) into ONE giant file with a `<teiCorpus>` root node. That's a TEI construction that basically involves multiple `<TEI>` elements as children of `<teiCorpus>`: yours has 46 children, all of which are readily accessible with XPath.

Now that I've committed and pushed those changes, I think you can finish drawing the line-graph with no trouble now! I re-ran the XSLT and the output SVG is properly drawing the first set of connecting lines on the "shot" phrase that you set up.

**Comment by ebeshero** [comment]
Also, I hope that teiCorpus file is useful! If you're making changes to the individual files, you can always just run the [teiCorpusTransform.xsl file](https://github.com/ahunker/Hamilton-Project/blob/master/Visualizations/PhrasesFrequency/teiCorpusTransform.xsl) over your collection of files to update the bundle. (Run it in oXygen just the way you do an XSLT that processes a collection() of files, by selecting a single XML file from the collection to transform.)

This should make life a little easier for XSLT processing!

**Comment by ahunker** [comment]
I finished the graph! Check it out in visualizations/PhrasesFrequency. Open the image in a new tab to get a better view of it. I'm thinking about adding a table below it that will show the individual counts of the phrases in each song to correspond with the graph above. Let me know what you think.

**Comment by ebeshero** [comment]
@ahunker It looks terrific--and very legible! "Waiting" seems like the most frequently recurring theme if I'm reading this correctly... 

Meanwhile, I got some help figuring out how to do `<xsl:for-each>` over a collection() of files (the way you were trying to do it in the first place), and I got *that* working, too (ha.) Naturally, I'm in a state of merge conflict. ;-) I'll sort it out--and I'll push two ways of making the same graph. You can decide which way you want to keep working once I've pushed this. And I'll probably want to reference this issue in future, next time I want to loop over a collection of files in XSLT! :-)

**Comment by ebeshero** [comment]
@ahunker @bsf15 **Do a Git Pull again!** 
 I've got the alternative XSLT prepared and outputting just the same as yours. All merge conflicts on my end are resolved, and I also did a little file clean-up and renaming so we can see what's what in the Visualizations/PhrasesFrequency directory.

There are *two* functional XSLT files here. 
1) XSLT FOR COLLECTION OF FILES: [Hamilton_Phrases_Frequency_SVG_Coll.xsl](https://github.com/ahunker/Hamilton-Project/blob/master/Visualizations/PhrasesFrequency/Hamilton_Phrases_Frequency_SVG_Coll.xsl)
2) XSLT FOR TEICORPUS (FILE): [Hamilton_Phrases_Frequency_SVG_teiCorpus.xsl](https://github.com/ahunker/Hamilton-Project/blob/master/Visualizations/PhrasesFrequency/Hamilton_Phrases_Frequency_SVG_teiCorpus.xsl)

The first one basically runs over the collection of separate files. The second one runs over that single TEI file I made out of the whole collection with teiCorpus. You can decide which one you want to keep using. I suspect the one that runs over the `collection()` is best because if you need to make changes to the individual song files, you won't need to reconstruct the teiCorpus file to process your graph anew! 

Hope this makes sense! I learned a lot today working with your files, so thanks for bearing with my tinkering! :-) Future classes will benefit.

**Comment by ebeshero** [comment]
@ahunker @bsf15 As for the graph, I think it's wonderfully legible and reveals some interesting patterns--were they what you expected to see? The color scheme is pretty clear to follow. 
You could write some JavaScript to show/hide specific lines on click of a line in your legend (or redo the legend do it's an HTML input form with checkboxes), but you'd just need to return to the XSLT to make sure you have attributes in place to toggle.  If you are strapped for time, though, I am not sure the JavaScript is necessary--it's easy to read this graph and interesting to see which phrases spike by comparison with the others! 

Do you want to take a look through the underlying markup to make sure you've caught all the phrases? And then, what I'd suggest next is...how about that making that timeline you've been talking about?

**Comment by bsf15** [comment]
The line graph for the phrases looks awesome! Definitely was expecting to see wait frequently, but it is interesting to really see where it most prominently pops up. 
I think main thing still needed to be done for the phrases is perhaps for the analysis text portion that will be accompanying the graph(if we are setting it up similar to the network graph for names and references) we should include all variations of the phrase that we marked up, especially for wait since there is a variety of phrases for that one. And maybe if we have time we could consider looking into who says which phrase the most to determine if any phrases are associated to particular characters since we already know off-hand that there is a correlation between phrases and characters, such as with Angelica and satisfied. I don't know for sure how we would go about doing that or if we would even have any worthwhile results from looking into that.
On a different note, I was going to start messing around with a timeline today, but when going through the songs and checking for the dates I'm starting to think that doing a timeline based off the dates in the songs wouldn't be worth it. If I did my search in exide right and counted right by going through the songs myself, there are only 5 distinct dates. For some reason, I thought there was way more dates, but I don't really know if a timeline would be interesting or provide any further insights due to the limited amount of dates in the actual songs.
I do want to make a similar network graph to the whole musical references one for each song though. After going through how to do it on Friday, I think I can definitely manage getting that done during the project meeting on Tuesday and I think that would be really interesting as not only would the graph be showing how often the speaker speaks and who is referenced, but it is also kinda showing who is in each song and who is often on stage together in a way.

**Comment by ebeshero** [comment]
@bsf15 These plans sound good to me. Here are some suggestions:

1) Just write a short XQuery (or XSLT) script to pull distinct values of the text() (or string()) contents of each phrase type. And use `normalize-space()` and maybe `lower-case()` to help eliminate duplicate results based on variations in white space and upper vs lower case. I think you've been doing similar kinds of things in other scripts, but I'm happy to help if you get stuck. 

2) How about just listing the 5 or so odd dates referenced in the musical? (And again, that's just a simple XQuery or XSLT output.) Sure, maybe it doesn't need to be a line, but you might use that info on one of your pages if you want to survey/discuss the historical content or historical referencing in the musical (which historical of biographical events are referenced directly?) I guess that's something people might be curious to learn about the musical?

3) Yay for the new network! This, I think, would be the one made by noticing literally who is present with a speaking/singing role with who else in each song--actually a little simpler to make than the one you were working on last week! I like the idea of showing who has the most prominence and is on stage most frequently with other characters.

**Comment by ahunker** [comment]
So I've finished the line graph and updated the visualizations page. @bsf15 If I've missed anything in the analysis, let me know. I can go through and figure out dates for songs if we really want to do a timeline. I can try to find at least a year to go with each song by looking at the events in the song or the songs before and after it. Did you want me to do that so you can make a timeline?
